# ---- GitHub文件源配置 ----
# GitHub用户名(不是昵称), 注意大小写
GitHubUserName: "first19326"
# GitHub主题仓库名称
GitHubRepositories: "Hexo-LiveForCode"


# ---- 基础信息配置 ----
# 博主名称, 文章后缀和主页图片上都会使用此名称
User: "Live For Code"
# 用户头像URL
UserAvatar: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/image/sidebar/avatar.jpg"
# 创建时间
WebsiteStartDate: "2020-01-01"
# 个人主页URL
Home: "https://worstone.cn"


# ---- 网站配置 ----
# 当前页失去焦点, 页面Title显示文字
WebsiteTitleBlur: "(◍´꒳`◍) Hi, Live For Code"
# 当前页失去焦点, 页面Title变化, 延时时间, 单位毫秒
WebsiteTitleBlurTimeOut: 500
# 当前页获取焦点, 页面Title显示文字, 显示后延时恢复原Title
WebsiteTitleFocus: "(*´∇｀*) 欢迎回来!"
# 当前页获取焦点, 页面title变化, 延时时间, 单位毫秒
WebsiteTitleFocusTimeOut: 1000
# 网站图标
WebsiteFavicon: 
  light: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/image/website/logo/logo.png"
  dark: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/image/website/logo/logo-dark.png"


# ---- 进度条配置 ----
ProgressBar:
  id: "topProgressBar"
  color: "#77B6FF"
  height: "2px"
  duration: 0.2


# ---- Loading配置 ----
Loading: 
  rebound: 
    tension: 16
    friction: 5
  spinner: 
    id: "spinner"
    radius: 90
    sides: 3
    depth: 4
    colors: 
      background: "#F0F0F0"
      stroke: "#272633"
      base: null
      child: "#272633"
    # When false the spring will reverse normally.
    alwaysForward: true
    # A number from 0.1 to 0.9 || null for full rotation. 
    restAt: 0.5
    renderBase: false


# ---- 页面动效配置 ----
# true || false, 是否渲染主页头图动效
HomeHeaderAnimationRendered: true
# 主页头图动效设置
HomeHeaderAnimation:    
  radius: 15
  density: 0.2
  # 颜色设置, "random" 为随机颜色
  color: "rgba(255, 255, 255, .2)"
  clearOffset: 0.3
# true || false, 是否渲染背景动效
BackAnimationRendered: true
# true || false, IE浏览器是否渲染背景动效（默认为false）
IEBrowserBackAnimationRendered: false
# 背景动效设置
BackAnimation:
  colorSaturation: "60%"
  colorBrightness: "50%"
  colorAlpha: 0.5
  colorCycleSpeed: 5
  verticalPosition: "random"
  horizontalSpeed: 200
  ribbonCount: 3
  strokeSize: 0
  parallaxAmount: -0.2
  animateSections: true


# ---- 主页配置 ----
# 主页图片URL, 推荐尺寸 >= 1920 * 1080, 支持多张, 每次刷新随机设置一张
HomeHeaderImage: 
  - "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/image/header/home.jpg"
  - "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/image/header/home.jpeg"
# 主页头图上的标语, 设置此选项会固定显示文字, 默认为空, 自动获取一句
HomeBannerText: ""


# ---- 文章详情页配置 ----
# 文章详情页图片URL, 支持多张, 每次刷新随机设置一张
ArticleHeaderImage: 
  - "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/image/header/article.jpg"


# ---- 其他页面配置 ----
# 其他页面头图上的标语, 设置此选项会固定显示文字, 默认为空, 自动获取一句
OtherBannerText: ""


# ---- 错误页面配置 ----
Error:
  icon: "icon-swimming"
  title: "PAGE NOT FOUND"
  content:
    - "很抱歉，您访问的页面不存在！"
    - "可能是输入地址有误或该地址已变更。"
  buttons:
    - 
      icon: "icon-home"
      text: "返回首页"
      href: "/"
      class: ""


# ---- 菜单配置 ----
# 菜单消息
MenuNotice:
  enable: true
  notice: "简单地活着，肆意而又精彩！"
  speed: 20
# 菜单列表
MenuList:
  -
    name: "首页"
    icon: "icon-home-fill"
    href: "/"
    type: "index"
    class: ""
    target: "_self"
  - 
    name: "分类"
    icon: "icon-folder-fill"
    href: "/category"
    type: "category"
    class: ""
    target: "_self"
  - 
    name: "标签"
    icon: "icon-discount-fill"
    href: "/tag"
    type: "tag"
    class: ""
    target: "_self"
  -
    name: "归档"
    icon: "icon-calendar-fill"
    href: "/archive"
    type: "archive"
    class: ""
    target: "_self"
  -
    name: "赞赏"
    icon: "icon-heart-fill"
    href: "/donate"
    type: "donate"
    class: ""
    target: "_self"
  -
    name: "关于"
    icon: "icon-about-fill"
    href: "/about"
    type: "about"
    class: ""
    target: "_self"
  -
    name: "订阅"
    icon: "icon-rss"
    href: "/atom.xml"
    type: ""
    class: ""
    target: "_blank"
  -
    name: "搜索"
    icon: "icon-search-menu"
    href: "javascript:;"
    type: ""
    class: "search"
    target: "_self"
  -
    name: "留言板"
    icon: "icon-comments-fill"
    href: "/comment"
    type: "comment"
    class: ""
    target: "_self"
  -
    name: "友情链接"
    icon: "icon-link"
    href: "/friend"
    type: "friend"
    class: ""
    target: "_self"
# 菜单链接
MenuLink:
  -
    name: "知乎"
    icon: "icon-zhihu"
    href: "https://zhihu.com/people/worstone-29"
    class: ""
    target: "_blank"
    image: ""
  -
    name: "微博"
    icon: "icon-weibo"
    href: "https://weibo.com/u/5749847477"
    class: ""
    target: "_blank"
    image: ""
  -
    name: "QQ"
    icon: "icon-qq"
    href: "javascript:;"
    class: "image"
    target: "_self"
    image: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/image/sidebar/qq.png"
  -
    name: "微信"
    icon: "icon-wechat"
    href: "javascript:;"
    class: ""
    target: "_self"
    image: ""
  -
    name: "GitHub"
    icon: "icon-github"
    href: "https://github.com/first19326"
    class: ""
    target: "_blank"
    image: ""


# ---- 页脚配置 ----
# 页脚样式
FooterStyle: 2
# 页脚标语
BottomText: "<div><span class='face'>ღゝ◡╹)ノ♡</span></div><div>【人生若只如初见<span><i class='iconfont icon-like-fill'></i></span>何事秋风悲画扇】</div><div>&copy; 2020-2023 WorstOne. All Rights Reserved.</div>"


# ---- 控制台输出 ----
ConsoleList:
  -
    - "Based on cnblogs theme SimpleMemory."
    - ""
  -
    - "SimpleMemory Author:"
    - "BNDong"
  -
    - "Theme:"
    - "LiveForCode"


# ---- 字体图标扩展 ----
FontIconExtend: ""


# ---- 赞赏配置 ----
Donate: 
  paypal : ""
  bitcoin: ""
  alipay : "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/image/donate/alipay.png"
  wechat : "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/image/donate/wechat.png"


# ---- Algolia配置 ----
Search:
  applicationID: "010C3EANT8"
  apiKey: "c7abab9f11b79102b9aff7fe6d41447d"
  indexName: "Notes"
  hits:
    page: 10
  labels:
    placeholder: "搜索"
    empty: "未发现与 「${query}」 相关的内容"
    stats: "${hits} 条相关条目，使用了 ${time} 毫秒"


# ---- Comment配置 ----
Comment:
  switch: true
  # 默认类型为 Valine, 可选项 Waline Valine
  type: "Valine" 

# ---- Valine配置 ----
Valine: 
  el: ".comments-content"
  appId: "srhKtvWPQTWYKh3qX8G8M7v0-gzGzoHsz"
  appKey: "8uVSP1q6UlALVC5igYfIfv2h"
  # 国内版本 LeanCloud 可以不用设置
  serverURLs: 
  placeholder: "你是我一生只会遇见一次的惊喜..."
  avatar: "mm"
  meta: "nick,mail,link"
  requiredFields: "nick,mail"
  pageSize: 5
  lang: "zh-cn"
  visitor: true
  enableQQ: true

# ---- Waline配置 ----
Waline:
  el: ".comments-content"
  serverURL: ""
  path: window.location.pathname
  meta: "['nick', 'mail', 'link']"
  requiredMeta: "['nick', 'mail']"
  pageSize: 10
  lang: "zh-cn"
  locale: 
      admin: "博主"
      anonymous: "匿名用户"
      sofa: "快来做第一个评论的人吧 ~"
      placeholder: "你是我一生只会遇见一次的惊喜..."
  dark: "html[color-scheme='dark']"
  search: false
  pageview: true
  comment: true
  copyright: false


# ---- Tocbot配置 ----
Tocbot: 
  switch: true
  tocSelector: ".toc"
  contentSelector: ".article-body"
  headingSelector: "h1, h2, h3, h4, h5"
  headingsOffset: 0
  scrollSmooth: true
  scrollSmoothOffset: -5
  positionFixedSelector: ".toc"
  positionFixedClass: "toc-fixed"


# ---- Require配置 ----
Require:
  baseUrl: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/js/"
  waitSeconds: 100


# ---- Music配置 ----
# 默认为Meting, 值包含APlayer, Meting
Music: 
  type: "Meting"
# APlayer
APlayer:
  container: ".aplayer"
  fixed: true 
  autoplay: false 
  loop: "all"
  order: "random"
  preload: "auto" 
  volume: 0.67 
  mutex: true
  lrcType: 3
  audio:
    -
      name: "Endless Tears"
      artist: "CLIFF EDGE"
      cover: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/music/cover/Endless Tears.jpg"
      url: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/music/song/Endless Tears.mp3"
      lrc: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/music/lrc/Endless Tears.lrc"
# Meting
Meting:
  api: "https://api.i-meto.com/meting/api"
  id: "3778678" 
  lrcshow: false 
  server: "netease" 
  type: "playlist"
  fixed: true 
  autoplay: false 
  loop: "all"
  order: "random"
  preload: "auto" 
  volume: 0.67 
  mutex: true


# ---- Mouse动画配置 ----
Mouse:
  enable: true
  options: 
    size: 6
    sizeF: 24


# ---- Lazy Load ----
LazyLoad:
  default: "/image/website/lazyload.svg"


# ---- Style配置 ----
Style:
  aplayer: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/css/APlayer.min.css"
  archive: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/css/archive.min.css"
  base: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/css/base.min.css"
  clipboard: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/css/clipboard.min.css"
  code: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/css/code.min.css"
  donate: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/css/donate.min.css"
  fancybox: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/css/jquery.fancybox.min.css"
  footer: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/css/footer.min.css"
  iconfont: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/iconfont/iconfont.min.css"
  index: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/css/index.min.css"
  menuBubble: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/css/menu-bubble.min.css"
  mouse: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/css/mouse.min.css"
  page: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/css/page.min.css"
  post: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/css/post.min.css"
  search: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/css/search.min.css"
  tocbot: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/css/tocbot.min.css"
  valine: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/css/valine.min.css"
  waline: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/css/waline.css"
  walineCustom: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/css/waline-custom.css"

# ---- Script配置 ----
Script:
  aplayer: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/js/APlayer.min.js"
  config: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/js/require.config.min.js"
  index: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/js/index.min.js"
  instantSearch: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/js/instantsearch.min.js"
  iscroll: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/js/iscroll.min.js"
  jQuery: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/js/jquery-3.4.1.min.js"
  loading: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/js/loading.min.js"
  meting: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/js/Meting.min.js"
  require: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/js/require.min.js"
  waline: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/js/waline.mjs"
  pageview: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/js/pageview.mjs"
  comment: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/js/comment.mjs"


# ---- Font配置 ----
Font:
  LongCang: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/font/LongCang.min.css"
  Monda: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/font/Monda.min.css"
  NotoSansSC: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/font/NotoSansSC.min.css"
  NotoSerifSC: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/font/NotoSerifSC.min.css"
  Playball: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/font/Playball.min.css"
  PTMono: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/font/PTMono.min.css"
  Roboto: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/font/Roboto.min.css"
  RobotoSlab: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/font/RobotoSlab.min.css"
  Rosario: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/font/Rosario.min.css"
  UbuntuMono: "https://cdn.jsdelivr.net/gh/first19326/cdn@master/static/font/UbuntuMono.min.css"


# ---- 文章尾缀配置 ----
Suffix: 
  about: "简单地活着, 肆意又精彩."


# ---- 主题信息配置 ----
Theme: 
  url: "https://github.com/first19326/Hexo-LiveForCode"
  name: "Hexo - Live For Code"